## myco_ethernet_name: network interface card name
## An Myco robot has 3 modules and 6 joints.
## All the parameters about joints should be in order of [J2, J1, J3, J4, J5, J6]
## reduction_ratios: The reduction ratios of the joints.
##                   Please refer to the paper attached with the robot.
## count_zeros: The encoder counts of the joints when they are in home position.
##              Please refer to the paper attached with the robot.
## axis_position_factors: The encoder resolution values. They are all 131072 in general.
## axis_torque_factors: They depend on the robot type.
##                      Myco3: [5251.283, 5251.283, 8533.125, 8533.125, 15975.05, 15975.05]
##                      Myco5: [2536.224, 2536.224, 5251.283, 5251.283, 15975.05, 15975.05]
##                      Myco10: [1365.332, 1365.332, 2536.224, 2536.224, 8533.125, 8533.125]


## example for myco_robot_bringup/config/myco_drivers.yaml

myco_ethernet_name: enp3s0

myco:
    slave_no: [2, 3, 4]
    joint_names: [myco_joint2, myco_joint1, myco_joint3, myco_joint4, myco_joint5, myco_joint6]
    reduction_ratios: [121, 121, 121, 121, 101, 101]
    count_zeros: [2957221, 9658298, 7019406, 5364946, -363218, -2134921]
    axis_position_factors: [131072, 131072, 131072, 131072, 131072, 131072]
    axis_torque_factors: [5251.283, 5251.283, 8533.125, 8533.125, 15975.05, 15975.05]
