myco_arm_controller:
  type: position_controllers/JointTrajectoryController
  joints:
     - myco_joint1
     - myco_joint2
     - myco_joint3
     - myco_joint4
     - myco_joint5
     - myco_joint6
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.1
  stop_trajectory_duration: 0.05
  state_publish_rate:  25
  action_monitor_rate: 10
